SPELLS = [
    {"name": "Cure for Boils", "flavor": "A potion that removes boils.",
     "ingredients": ["snake fangs", "pungous onions", "dried nettles", "flobberworm mucus",
                      "powdered ginger root", "shrake spines", "stewed horned slugs", "porcupine quills"],
     "expected_stirs": 19},
    {"name": "Forgetfulness Potion", "flavor": "Causes an unknown degree of memory loss in the drinker.",
     "ingredients": ["lethe river water", "valerian sprigs", "mistletoe berries"],
     "expected_stirs": 9},
    {"name": "Pompion Potion", "flavor": "Temporarily turns the drinker's head into a pumpkin.",
     "ingredients": ["flitterby moth", "bouncing bulb", "foxglove"],
     "expected_stirs": 9},
    {"name": "Fire Protection Potion", "flavor": "Lets the drinker move through flames unscathed.",
     "ingredients": ["bursting mushrooms", "salamander blood", "wartcap powder"],
     "expected_stirs": 9},
    {"name": "Hair-Raising Potion", "flavor": "Makes the drinker's hair stand on end.",
     "ingredients": ["rat tails", "porcupine quills", "billywig stings"],
     "expected_stirs": 9},
    {"name": "Confusing Concoction", "flavor": "Causes confusion.",
     "ingredients": ["scurvy grass", "lovage", "sneezewort"],
     "expected_stirs": 9},
    {"name": "Doxycide", "flavor": "A foul-smelling potion used to paralyze Doxies.",
     "ingredients": ["bundimun acid", "streeler shells", "dragon liver",
                      "hemlock essence", "cowbane essence", "tormentil tincture"],
     "expected_stirs": 15},
    {"name": "Wit-Sharpening Potion", "flavor": "Allows the drinker to think more clearly.",
     "ingredients": ["ginger root", "armadillo bile", "ground scarab beetles"],
     "expected_stirs": 9},
    {"name": "Calming Draught", "flavor": "Calms a person down after shock or trauma.",
     "ingredients": ["lavender", "crocodile heart", "peppermint"],
     "expected_stirs": 9},
    {"name": "Pepperup Potion", "flavor": "Cures the common cold and warms the recipient.",
     "ingredients": ["bicorn horn", "mandrake root", "jewelweed"],
     "expected_stirs": 9},
    {"name": "Ageing Potion", "flavor": "Temporarily makes the drinker older.",
     "ingredients": ["newt spleens", "bananas", "orange snake", "green leaf"],
     "expected_stirs": 11},
    {"name": "Strengthening Solution", "flavor": "Grants the drinker immense strength.",
     "ingredients": ["salamander blood", "powdered griffin claw", "fanged geranium", "arm bone", "snake fang"],
     "expected_stirs": 13},
    {"name": "Befuddlement Draught", "flavor": "Makes the drinker belligerent and reckless.",
     "ingredients": ["scurvy grass", "lovage", "sneezewort"],
     "expected_stirs": 9},
    {"name": "Erumpent Potion", "flavor": "Highly explosive when touched by an outside source.",
     "ingredients": ["erumpent horn", "erumpent tail", "exploding fluid"],
     "expected_stirs": 9},
    {"name": "Dragon Tonic", "flavor": "A healing potion used to cure sick dragons.",
     "ingredients": ["eagle owl feather", "peacock feathers", "giant purple toad warts"],
     "expected_stirs": 9},
    {"name": "Invisibility Potion", "flavor": "Grants temporary invisibility.",
     "ingredients": ["cherries", "chicken", "spiders"],
     "expected_stirs": 9},
    {"name": "Love Potion Antidote", "flavor": "Serves as an antidote for love potions.",
     "ingredients": ["wiggentree twigs", "castor oil", "extract of gurdyroot"],
     "expected_stirs": 9},
    {"name": "Memory Potion", "flavor": "Improves the drinker's memory and mental cognition.",
     "ingredients": ["jobberknoll feathers", "stewed mandrake", "powdered sage", "galanthus nivalis"],
     "expected_stirs": 11},
    {"name": "Exstimulo Potion", "flavor": "Increases the spell power of a single cast.",
     "ingredients": ["re'em blood", "granian hair", "snowdrop", "bitter root"],
     "expected_stirs": 11},
    {"name": "Baruffio's Brain Elixir", "flavor": "Supposedly increases the drinker's brain power.",
     "ingredients": ["leaping toadstools", "frog brains", "runespoor eggs", "powdered dragon claw"],
     "expected_stirs": 11},
]
